import uuid
from datetime import datetime
from app.extensions import db


def gen_uuid():
    return str(uuid.uuid4())


# ---------------------------------------------------------
# Insight: the "Monthly AI Analysis" / "AI Health Snippet"
# blocks shown on dashboard.html and insights.html.
# Generated by your ML model (or seeded manually for now).
# ---------------------------------------------------------
class Insight(db.Model):
    __tablename__ = "insights"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    user_id = db.Column(db.String(36), db.ForeignKey("users.id"), nullable=False, index=True)

    type = db.Column(db.String(30), default="monthly_analysis")  # monthly_analysis | health_snippet
    title = db.Column(db.String(150), nullable=False)
    body = db.Column(db.Text, nullable=False)
    is_new = db.Column(db.Boolean, default=True)

    cta_label = db.Column(db.String(80), nullable=True)   # e.g. "Review Dining Transactions"
    cta_link = db.Column(db.String(150), nullable=True)   # e.g. "/transactions"

    generated_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    def to_dict(self):
        return {
            "id": self.id,
            "type": self.type,
            "title": self.title,
            "body": self.body,
            "isNew": self.is_new,
            "cta": (
                {"label": self.cta_label, "link": self.cta_link}
                if self.cta_label
                else None
            ),
            "generatedAt": self.generated_at.isoformat() if self.generated_at else None,
        }


# ---------------------------------------------------------
# SmartTip: the "Smart Tips" list on insights.html
# ---------------------------------------------------------
class SmartTip(db.Model):
    __tablename__ = "smart_tips"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    user_id = db.Column(db.String(36), db.ForeignKey("users.id"), nullable=False, index=True)

    icon = db.Column(db.String(50), default="lightbulb")
    icon_color = db.Column(db.String(20), default="#F59E0B")
    icon_bg = db.Column(db.String(20), default="#fef3c7")
    title = db.Column(db.String(150), nullable=False)
    description = db.Column(db.Text, nullable=False)
    is_dismissed = db.Column(db.Boolean, default=False)

    created_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    def to_dict(self):
        return {
            "id": self.id,
            "icon": self.icon,
            "iconColor": self.icon_color,
            "iconBg": self.icon_bg,
            "title": self.title,
            "description": self.description,
        }


# ---------------------------------------------------------
# CategorySpend: precomputed category breakdown for the
# donut chart on insights.html. One row per user/category/period.
# ---------------------------------------------------------
class CategorySpend(db.Model):
    __tablename__ = "category_spend"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    user_id = db.Column(db.String(36), db.ForeignKey("users.id"), nullable=False, index=True)

    period = db.Column(db.String(7), nullable=False, index=True)  # "YYYY-MM"
    category = db.Column(db.String(80), nullable=False)
    amount_cents = db.Column(db.BigInteger, nullable=False)
    pct = db.Column(db.Float, nullable=False)  # percentage of total spend
    color = db.Column(db.String(20), default="#0058be")

    def to_dict(self):
        return {
            "category": self.category,
            "amount": round(self.amount_cents / 100, 2),
            "pct": self.pct,
            "color": self.color,
        }
